spring:
  profiles:
    active: development  
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bluefox
    username: postgres
    password: root
# JPA properties
  jpa:
#    generate-ddl: true
    hibernate:
      ddl-auto: update    properties:      master:
        masterId: ABcde
